--
-- File generated with SQLiteStudio v3.2.1 on ju. abr. 27 18:48:13 2023
--
-- Text encoding used: System
--
PRAGMA foreign_keys = off;
BEGIN TRANSACTION;

-- Table: HOTEL
CREATE TABLE HOTEL (ID_HOTEL STRING (20) NOT NULL REFERENCES REVIEWS (ID_HOTEL), NAME STRING (100), DESCRIPTION STRING (4000), ID_LOCATION STRING (20) REFERENCES LOCATION (ID_LOCATION), PRICE INTEGER, ID STRING (20) PRIMARY KEY NOT NULL UNIQUE, IMAGE STRING (100));
INSERT INTO HOTEL (ID_HOTEL, NAME, DESCRIPTION, ID_LOCATION, PRICE, ID, IMAGE) VALUES (1, 'RIU', 'RIU DESC', 1, 75, 1, '/image/pictureRIU.jpg');
INSERT INTO HOTEL (ID_HOTEL, NAME, DESCRIPTION, ID_LOCATION, PRICE, ID, IMAGE) VALUES (2, 'HILTON', 'HILTON DESC', 2, 200, 2, '/images/pictureHilton.jpg');
INSERT INTO HOTEL (ID_HOTEL, NAME, DESCRIPTION, ID_LOCATION, PRICE, ID, IMAGE) VALUES (1, 'RIU', 'RIU DESC', 1, 75, 3, '/images/pictureRIU.jpg');

COMMIT TRANSACTION;
PRAGMA foreign_keys = on;
