--
-- File generated with SQLiteStudio v3.2.1 on ju. abr. 27 18:48:54 2023
--
-- Text encoding used: System
--
PRAGMA foreign_keys = off;
BEGIN TRANSACTION;

-- Table: LOCATION
CREATE TABLE LOCATION (ID_LOCATION STRING (20) PRIMARY KEY NOT NULL UNIQUE, NAME STRING (100));
INSERT INTO LOCATION (ID_LOCATION, NAME) VALUES (3, 'MADRID');
INSERT INTO LOCATION (ID_LOCATION, NAME) VALUES (1, 'LONDON');
INSERT INTO LOCATION (ID_LOCATION, NAME) VALUES (2, 'PARIS');

COMMIT TRANSACTION;
PRAGMA foreign_keys = on;
